---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Сайт должен иметь мобильную версию.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - На сайте реализована функция смена языка на Русский и Английский.
  - На сайте есть кнопка переключения страницы каталого товара (Предыдущая/Следующая).
  - Есть возможность удалить товар из корзины.
  - Кнопка "Оформить заказ" должна быть зелёного цвета.
  - Кнока "Очистить корзину" должна быть красного цвета.
  - На позиции товара в корзине кнопка "Удалить" должна быть красного цвета.
  - Над ссылкой "Корзина" должно быть указано колличество позиций добавленных в корзину.
  - На сайте должна быть реализована форма регистрации.
  - Оформить заказ может только зарегестрированный пользователь с контактными данными.
